FROM golang:onbuild
MAINTAINER brann <brann@cosmos.io>

# Install Cosmos
ENV COSMOS_PORT 8081
ENV INFLUXDB_HOST influxdb
ENV INFLUXDB_PORT 8086
ENV INFLUXDB_USERNAME root
ENV INFLUXDB_PASSWORD root
ENV INFLUXDB_DATABASE cosmos

EXPOSE 8081
